-- Korisnici moraju vidjeti sve dostupne terene u njihovoj blizini (po kvartovima) te vidjeti postoji li slobodan termin.

-- tereni u kvartu
SELECT KVART.IME, TEREN.IME 
FROM TEREN
INNER JOIN KVART
ON TEREN.KVART_ID = KVART.KVART_ID

-- tereni u kvartu sa slobodnim terminom (treba jos malo sredit, vjv LEFT JOIN...)
SELECT REZERVACIJA.POCETAK, KVART.IME, TEREN.IME 
FROM TEREN
INNER JOIN KVART
ON TEREN.KVART_ID = KVART.KVART_ID
INNER JOIN REZERVACIJA
ON TEREN.KVART_ID = REZERVACIJA.TEREN_ID

--  Korisnik može vidjeti i povijest svojih rezervacija.

SELECT * FROM REZERVACIJA WHERE OIB IN ('311')



-- Dostupni sadrzaji za sportski objekt

SELECT SPORTSKI_OBJEKT.IME, DODATNI_SADRZAJ.TIP
FROM SPORTSKI_OBJEKT
INNER JOIN OBJEKT_SADRZAJ
ON OBJEKT_SADRZAJ.SPORTSKI_OBJEKT_ID = SPORTSKI_OBJEKT.SPORTSKI_OBJEKT_ID
INNER JOIN DODATNI_SADRZAJ
ON DODATNI_SADRZAJ.DODATNI_SADRZAJ_ID = objekt_sadrzaj.dodatni_sadrzaj_id


-- Dostupni rekviziti

SELECT REKVIZIT.TIP 
FROM REKVIZIT
INNER JOIN SPORTSKI_OBJEKT
ON SPORTSKI_OBJEKT.SPORTSKI_OBJEKT_ID = REKVIZIT.SPORTSKI_OBJEKT_ID


SELECT * FROM TEREN

SELECT * FROM SPORTSKI_OBJEKT

SELECT * FROM KVART

SELECT * FROM REZERVACIJA
