INSERT INTO system.KORISNIK(OIB,IME,PREZIME) VALUES ('0541','Marko','Markic');
INSERT INTO system.KORISNIK(OIB,IME,PREZIME) VALUES ('0311','Ivo','Ivic');
INSERT INTO system.KORISNIK(OIB,IME,PREZIME) VALUES ('0515','Lovro','Loric');



INSERT INTO system.GRAD(GRAD_ID,IME,DRZAVA) VALUES ('1','Zagreb','RH');
INSERT INTO system.GRAD(GRAD_ID,IME,DRZAVA) VALUES ('2','Osijek','RH');



INSERT INTO system.KVART(KVART_ID,IME,GRAD_ID) VALUES ('1','Trnje','1');
INSERT INTO system.KVART(KVART_ID,IME,GRAD_ID) VALUES ('2','Tresnjevka','1');
INSERT INTO system.KVART(KVART_ID,IME,GRAD_ID) VALUES ('3','Kruge','1');
INSERT INTO system.KVART(KVART_ID,IME,GRAD_ID) VALUES ('4','Spansko','1');

INSERT INTO system.SPORTSKI_OBJEKT(SPORTSKI_OBJEKT_ID,IME,WEB_STRANICA, GRAD_ID) VALUES ('1','SRC Trnje','www.srctrnje.com','1');
INSERT INTO system.SPORTSKI_OBJEKT(SPORTSKI_OBJEKT_ID,IME,WEB_STRANICA, GRAD_ID) VALUES ('2','Centar Sporta','www.centsport.com','1');
INSERT INTO system.SPORTSKI_OBJEKT(SPORTSKI_OBJEKT_ID,IME,WEB_STRANICA, GRAD_ID) VALUES ('3','Sport Sport','www.sportsport.com','1');


INSERT INTO system.TEREN(TEREN_ID,IME,VRSTA_TERENA,NATKRIVEN,SPORTSKI_OBJEKT_ID,KVART_ID) VALUES ('1','Nogometni teren Lopta','Nogomet','T','1','1');
INSERT INTO system.TEREN(TEREN_ID,IME,VRSTA_TERENA,NATKRIVEN,SPORTSKI_OBJEKT_ID,KVART_ID) VALUES ('2','Nogos ABC','Nogomet','T','1','1');
INSERT INTO system.TEREN(TEREN_ID,IME,VRSTA_TERENA,NATKRIVEN,SPORTSKI_OBJEKT_ID,KVART_ID) VALUES ('3','Teren nogo','Nogomet','T','1','1');

INSERT INTO system.REZERVACIJA(REZERVACIJA_ID,POCETAK,KRAJ,TEREN_ID,OIB) VALUES ('1','12:00','13:00','1','0541');
INSERT INTO system.REZERVACIJA(REZERVACIJA_ID,POCETAK,KRAJ,TEREN_ID,OIB) VALUES ('2','19:00','20:00','1','0311');
INSERT INTO system.REZERVACIJA(REZERVACIJA_ID,POCETAK,KRAJ,TEREN_ID,OIB) VALUES ('3','09:00','10:00','2','0311');

INSERT INTO system.REKVIZIT(REKVIZIT_ID,TIP,IZNAJMLJEN,SPORTSKI_OBJEKT_ID,REZERVACIJA_ID) VALUES ('1','Nogometna lopta','T','1','1');
INSERT INTO system.REKVIZIT(REKVIZIT_ID,TIP,IZNAJMLJEN,SPORTSKI_OBJEKT_ID,REZERVACIJA_ID) VALUES ('2','Nogometna lopta','T','1','1');

INSERT INTO system.DODATNI_SADRZAJ(DODATNI_SADRZAJ_ID,TIP) VALUES('1','Kafic');
INSERT INTO system.DODATNI_SADRZAJ(DODATNI_SADRZAJ_ID,TIP) VALUES('2','Tusevi');
INSERT INTO system.DODATNI_SADRZAJ(DODATNI_SADRZAJ_ID,TIP) VALUES('3','Teretana');

INSERT INTO system.OBJEKT_SADRZAJ(SPORTSKI_OBJEKT_ID,DODATNI_SADRZAJ_ID) VALUES('1','1');
INSERT INTO system.OBJEKT_SADRZAJ(SPORTSKI_OBJEKT_ID,DODATNI_SADRZAJ_ID) VALUES('1','2');